version: "3.8"
services:
  rabbitmq: 
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_USER=user
    ports:
      # RabbitMQ instance
      - '5672:5672'
      # Web interface
      - '15672:15672'